# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YDBannerView' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YDBannerView
pod 'SDWebImage'

  target 'YDBannerViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YDBannerViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
